server:
  port: 8083

### config he thong

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thuy_linh?serverTimezone=GMT%2B7&useLegacyDatetimeCode=false
    username: root
    password: quang1998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
app:
  jwt:
    secret: KYIVtA7915PUEWTqTca74sENpw48u7nkzSJiJmitF7D2PJWOu
    expiredTime: 6000000


  #validate: validate the schema, makes no changes to the database.
  #update: update the schema.
  #create: creates the schema, destroying previous data.
  #create-drop: drop the schema at the end of the session.
  #none: no activity to DB